pipeline:
  name: finalbuild
  identifier: finalbuild
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: gitHubConnector
        repoName: windows-runner
        build: <+input>
  stages:
    - stage:
        name: buil
        identifier: buil
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: test
              namespace: harness-delegate-ng
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: BuildAndPushACR
                  name: BuildAndPushACR_1
                  identifier: BuildAndPushACR_1
                  spec:
                    connectorRef: ACRAZURECONNNECTIVITY
                    repository: mytestreg.azurecr.io/test
                    tags:
                      - latest
