name: Deploy to Azure SQL Database
on:
  push:
    branches:
       - test

  # pull_request:
  #   branches: [ master ]
      
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
  
jobs:

  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup msbuild PATH
      uses: microsoft/setup-msbuild@v1.0.2
